### ISSUE TITLE
No error, no output

### ISSUE THREAD

**Issue by Atheryl** [ayazshah2/nice-invoice#4]
Hi,

 As of today's test, with the sample on npm.js.com the code is running without error, but no PDFs are generated.
 
 Thanks,

**Comment by ayazshah2** [comment]
Hi @Atheryl,
I just checked it, it is working fine. Can you please let me know if you are following the documentation?
Thank you

**Comment by Atheryl** [comment]
It was entirely my fault. I had a await that wasn't working apparently and the function was exiting before the PDF were written. Apologies.
